package com.example.TaskFlow.Enum;

public enum EventType {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,
    PROJECT_DELETED,
}
